=== haroonrasheed333/ProjectHTML5/proj1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Features">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Feature"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Feature">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Title"/>
        <xs:element maxOccurs="unbounded" ref="Spec"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Title" type="xs:string"/>
  <xs:element name="Spec">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="Description"/>
        <xs:element ref="W3CLink"/>
        <xs:element ref="Browsers"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="status" use="required" type="status"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Description" type="xs:string"/>
  <xs:element name="W3CLink" type="xs:anyURI"/>
  <xs:element name="Browsers">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Browser"/>
        <xs:sequence minOccurs="0">
          <xs:element ref="Name"/>
          <xs:element ref="Version"/>
        </xs:sequence>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Browser">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Name"/>
        <xs:element ref="Version"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Name" type="xs:string"/>
  <xs:element name="Version" type="xs:decimal"/>
  
  <xs:simpleType name="status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="WD"/>
      <xs:enumeration value="CR"/>
      <xs:enumeration value="PER"/>
      <xs:enumeration value="PR"/>
      <xs:enumeration value="REC"/>
      <xs:enumeration value="NOTE"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== haroonrasheed333/ProjectHTML5/proj1_v3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Features xmlns:ns="http://www.example.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.com proj1.xsd">
    <Feature>
        <Title>File Access</Title>
        <Spec id="fileapi" status="WD">
            <Name>File API</Name>
            <Description>Method of manipulating file objects in web applications client-side, as well as programmatically selecting them and accessing their data.</Description>
            <Abstract> This specification provides an API for representing file objects in web applications, as well as programmatically selecting them and accessing their data. This includes:
                
                A FileList interface, which represents an array of individually selected files from the underlying system. The user interface for selection can be invoked via &lt;input type=&quot;file&quot;&gt;, i.e. when the input element is in the File Upload state [HTML] .
                    A Blob interface, which represents immutable raw binary data, and allows access to ranges of bytes within the Blob object as a separate Blob.
                    A File interface, which includes readonly informational attributes about a file such as its name and the date of the last modification (on disk) of the file.
                    A FileReader interface, which provides methods to read a File or a Blob, and an event model to obtain the results of these reads.
                    A URL scheme for use with binary data such as files, so that they can be referenced within web applications.
                    Additionally, this specification defines objects to be used within threaded web applications for the synchronous reading of files.
                    
                    The section on Requirements and Use Cases [REQ] covers the motivation behind this specification.
                    
                    This API is designed to be used in conjunction with other APIs and elements on the web platform, notably: XMLHttpRequest (e.g. with an overloaded send() method for File or Blob objects), postMessage, DataTransfer (part of the drag and drop API defined in [HTML,]) and Web Workers. Additionally, it should be possible to programmatically obtain a list of files from the input element when it is in the File Upload state[HTML]. These kinds of behaviors are defined in the appropriate affiliated specifications.</Abstract>
            <W3CLink>http://www.w3.org/TR/FileAPI</W3CLink>
            <Browsers>
                <Browser>
                    <Name>Chrome</Name>
                    <Version>13</Version>
                </Browser>
                <Browser>
                    <Name>Firefox</Name>
                    <Version>4</Version>
                </Browser>
                <Browser>
                    <Name>Safari</Name>
                    <Version>6</Version>
                </Browser>
                <Browser>
                    <Name>Opera</Name>
                    <Version>12</Version>
                </Browser>                
                <Browser>
                    <Name>IE</Name>
                    <Version>10</Version>
                </Browser>
                <Browser>
                    <Name>IOS Safari</Name>
                    <Version>6.1</Version>
                </Browser>
                <Browser>
                    <Name>Opera Mobile</Name>
                    <Version>0</Version>
                </Browser>
            </Browsers>
        </Spec>
        
        <Spec id="file-reader-api" status="WD">
            <Name>File Reader API</Name>
            <Description>Method of reading the contents of a File or Blob object into memory</Description>
            <W3CLink>http://www.w3.org/TR/FileAPI/#dfn-filereader</W3CLink>
            <Browsers>
                <Browser>
                    <Name>Chrome</Name>
                    <Version>6</Version>
                </Browser>
                <Browser>
                    <Name>Firefox</Name>
                    <Version>4</Version>
                </Browser>
                <Browser>
                    <Name>Safari</Name>
                    <Version>6</Version>
                </Browser>
                <Browser>
                    <Name>Opera</Name>
                    <Version>12</Version>
                </Browser>                
                <Browser>
                    <Name>IE</Name>
                    <Version>10</Version>
                </Browser>
                <Browser>
                    <Name>IOS Safari</Name>
                    <Version>6.1</Version>
                </Browser>
                <Browser>
                    <Name>Android</Name>
                    <Version>3</Version>
                </Browser>
                <Browser>
                    <Name>Opera Mobile</Name>
                    <Version>0</Version>
                </Browser>
            </Browsers>
        </Spec>
        
        <Spec id="file-system-api" status="WD">
            <Name>Filesystem and FileWriter API</Name>
            <Description>Method of reading and writing files to a sandboxed file system.</Description>
            <Abstract>This specification defines an API to navigate file system hierarchies, and defines a means by which a user agent may expose sandboxed sections of a user's local filesystem to web applications. It builds on [FILE-WRITER-ED], which in turn built on [FILE-API-ED], each adding a different kind of functionality.</Abstract>
            <W3CLink>http://www.w3.org/TR/file-system-api/</W3CLink>
            <Browsers>
                <Browser>
                    <Name>Chrome</Name>
                    <Version>13</Version>
                </Browser>
                
                <Browser>
                    <Name>Opera</Name>
                    <Version>15</Version>
                </Browser>                
                
                <Browser>
                    <Name>Opera Mobile</Name>
                    <Version>0</Version>
                </Browser>
            </Browsers>
        </Spec>
        
        <Spec id="blob-constructing" status="WD">
            <Name>Blob constructing</Name>
            <Description>Construct Blobs (binary large objects) either using the BlobBuilder API (deprecated) or the Blob constructor.</Description>
            <W3CLink>http://www.w3.org/TR/file-writer-api/#the-blobbuilder-interface</W3CLink>
            <Browsers>
                <Browser>
                    <Name>Chrome</Name>
                    <Version>20</Version>
                </Browser>
                <Browser>
                    <Name>Firefox</Name>
                    <Version>13</Version>
                </Browser>
                <Browser>
                    <Name>Safari</Name>
                    <Version>6</Version>
                </Browser>
                <Browser>
                    <Name>Opera</Name>
                    <Version>15</Version>
                </Browser>                
                <Browser>
                    <Name>IE</Name>
                    <Version>10</Version>
                </Browser>
                <Browser>
                    <Name>IOS Safari</Name>
                    <Version>6.1</Version>
                </Browser>
                
                <Browser>
                    <Name>Opera Mobile</Name>
                    <Version>0</Version>
                </Browser>
            </Browsers>
        </Spec>
        
        <Spec id="blob-urls" status="WD">
            <Name>Blob URLs</Name>
            <Description>Method of creating URL handles to the specified File or Blob object.</Description>
            <W3CLink>http://www.w3.org/TR/FileAPI/#url</W3CLink>
            <Browsers>
                <Browser>
                    <Name>Chrome</Name>
                    <Version>8</Version>
                </Browser>
                <Browser>
                    <Name>Firefox</Name>
                    <Version>4</Version>
                </Browser>
                <Browser>
                    <Name>Safari</Name>
                    <Version>6</Version>
                </Browser>
                <Browser>
                    <Name>Opera</Name>
                    <Version>15</Version>
                </Browser>                
                <Browser>
                    <Name>IE</Name>
                    <Version>10</Version>
                </Browser>
                <Browser>
                    <Name>IOS Safari</Name>
                    <Version>6.1</Version>
                </Browser>
                <Browser>
                    <Name>Android</Name>
                    <Version>4</Version>
                </Browser>
                <Browser>
                    <Name>Opera Mobile</Name>
                    <Version>0</Version>
                </Browser>
            </Browsers>
        </Spec>        
    </Feature> 
    
    <Feature>
        <Title>Presentation</Title>
        <Spec id="css-3d-transforms" status="WD">
            <Name>CSS 3D Transforms</Name>
            <Description>Method of transforming an element in the third dimension</Description>
            <Abstract>CSS transforms allows elements styled with CSS to be transformed in two-dimensional or three-dimensional space. This specification is the convergence of the CSS 2D transforms, CSS 3D transforms and SVG transforms specifications.</Abstract>
            <W3CLink>http://www.w3.org/TR/css3-transforms/</W3CLink>
            <Browsers>
                <Browser>
                    <Name>Chrome</Name>
                    <Version>12</Version>
                </Browser>
                <Browser>
                    <Name>Firefox</Name>
                    <Version>10</Version>
                </Browser>
                <Browser>
                    <Name>Safari</Name>
                    <Version>4</Version>
                </Browser>
